import type { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Orange Portfólio',
  description: 'Generated by Squard-30',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
